### PR TITLE
Add docker development setup

### PR DESCRIPTION
**Pull request by kelunik**

### CODE REVIEW

**Review by saundefined — APPROVED** [review]

**Comment by nikic** [comment]
This will very likely break rsync.

**Comment by nikic** [comment]
Specifically, I'm not sure what will happen with https://github.com/php/systems/blob/841f4d366db578a61cebdaeb578bd2ca14a23924/update-mirrors#L22-L27 after the submodule is added here. Will things work fine even though there already is a repository at that location?

**Comment by nikic** [comment]
> Specifically, I'm not sure what will happen with https://github.com/php/systems/blob/841f4d366db578a61cebdaeb578bd2ca14a23924/update-mirrors#L22-L27 after the submodule is added here. Will things work fine even though there already is a repository at that location?

Okay, I just tried this locally, and it seems to work just fine! In that case just two requests:

 * Can you please also update https://github.com/php/web-master/blob/main/src/DB.php to use the credentials from env vars? Some of the code is based on PDO, and I've just added the common function to have the credentials only in one place (or at least one place per extension...)
 * I would suggest not checking in the symlink, otherwise the `.git` directory will be exposed to the web, which seems like a not so good idea. Note that the production system doesn't need `shared/` to be web-readable, this is only needed for local development.

**Comment by kelunik** [comment]
@nikic The linked script should continue working, as a submodule is basically just a repository with a version reference stored in the parent repository.

Sure, will update it, it didn't exist before. ;-)

**Comment by kelunik** [comment]
@nikic Done. I've changed from a symlink to separate static file serving. Credentials are now centralized for `mysql` and `PDO`.

**Review by nikic — APPROVED** [review]

**Pull request merged**
